[loggers]
keys=root,main,createConfig,doStuff

[handlers]
keys=handMain,handRotating,handCreateConfig,handDoStuff

[formatters]
keys=form01

[logger_root]
level=DEBUG
handlers=handRotating

[logger_main]
level=DEBUG
handlers=handMain
qualname=__main__
propagate=1

[logger_createConfig]
level=DEBUG
handlers=handCreateConfig
qualname=createConfig
propagate=1

[logger_doStuff]
level=DEBUG
handlers=handDoStuff
qualname=doStuff
propagate=1

[handler_handRotating]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=form01
# args=('./logs/rootating.log', 'W0', 5, 'utf-8')
args=('./logs/root.log', 'D', 1, 5, 'utf-8')

[handler_handMain]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=form01
args=('./logs/main.log', 'D', 1, 5, 'utf-8')

[handler_handCreateConfig]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=form01
args=('./logs/createConfig.log', 'D', 1, 5, 'utf-8')

[handler_handDoStuff]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=form01
args=('./logs/doStuff.log', 'D', 1, 5, 'utf-8')

[formatter_form01]
format=$asctime ($name):$levelname - $message
datefmt=
style=$
validate=True
class=logging.Formatter